config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :views
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'landings#index'
  resources :users
  resources :landings
  # Nest the reviews routes under the product routes so that the Reviews controller can be used for review actions 
  resources :products do
  	resources :reviews
  end
  # Nest the routes for comments under topics so that the Comments controller can be used for comment actions
  resources :topics do
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :topic, inverse_of: :comments
	belongs_to :user, inverse_of: :comments
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :reviews, inverse_of: :product, dependent: :destroy
	has_many :users, through: :reviews
	accepts_nested_attributes_for :reviews, allow_destroy: true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :product, inverse_of: :reviews
	belongs_to :user, inverse_of: :reviews
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :comments, inverse_of: :topic, dependent: :destroy
	has_many :users, through: :comments
	accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, inverse_of: :user, dependent: :destroy
  has_many :products, through: :reviews
  has_many :comments, inverse_of: :user, dependent: :destroy
  has_many :topics, through: :comments
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_topic
	before_action :find_comment, only: [:edit, :update, :destroy]

	def index
		@comments = Comment.all
	end

	def show
		@comment = Comment.find(params[:id])
	end
	
	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		@comment.topic_id = @topic.id

		if @comment.save
			redirect_to topic_path(@topic)
		else
			redirect_to 'new'
		end
	end

	def edit
	end

	def update
		@comment = Comment.find(params[:id])
		if @comment.update(comment_params)
			redirect_to topic_path(@topic)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to topic_path(@topic)
	end


	private

	def comment_params
		params.require(:comment).permit(:comment, :user_id)
	end

	def find_topic
		@topic = Topic.find(params[:topic_id])
	end

	def find_comment
		@comment = Comment.find(params[:id])
	end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
	before_action :authenticate_user!, only: :secure

	def index
		if current_user
			puts "I'm logged in as #{current_user.email}"
		else
			puts "I'm not logged in"
		end
	end

	def secure
		id = current_user.id
		user = User.find(id)

		puts "============"
		p user
		puts "============"
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@user = current_user.id
		@products = Product.all

		puts @products
	end

	def show
		@user = current_user.id
		@product = Product.find(params[:id])
		# Assign an instance variable and make a conditional that evaluates how many reviews have been recorded. average out the total and round it.
		if @product.reviews.blank?
			@average_review = 0
		else
			@average_review = @product.reviews.average(:rating).round(2)
		end
	end

	def new
		@user = current_user.id
		@product = Product.new
	end

	def create
		@user = current_user.id
		@product = Product.new(product_params)
		if @product.save
			redirect_to product_url(@product)
		else
			redirect_to product_new_url
		end
	end

	def edit
		@user = current_user
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)

			redirect_to product_url(@product)
		else
			redirect_to product_edit_url
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end


	private

	def product_params
		params.require(:product).permit(:name, :description, :img)
	end

# , :reviews_attributes => [:id, :title, :review, :rating, :_destroy, :user_id]  // old way to send reviews to products
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_product
	before_action :find_review, only: [:edit, :update, :destroy]

	def index
		@reviews = Review.all
	end

	def show
		@review = Review.find(params[:id])
	end

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		# set the current product.id as the reference id to the new review when it is created.
		@review.product_id = @product.id

		# set the user_id under the review model to the current_user that is signed in.
		@review.user_id = current_user.id
		
		# if the review saves, redirect to the product show page, else redirect to the new form.
		if @review.save
			redirect_to product_path(@product)
		else
			redirect_to 'new'
		end
	end

	def edit
		# no longer need to define the Review.find statement because I assigned it to a private method and used the before_action at the top.
	end

	def update
		@review = Review.find(params[:id])
		if @review.update(review_params)
			redirect_to product_path(@product)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to product_path(@product)
	end




	private
	def review_params
		params.require(:review).permit(:title, :review, :rating)
	end

	# We want to find the current product we are on and set it to @product so that we can access the id in the review create action
	def find_product
		@product = Product.find(params[:product_id])
	end
	# Only use find_review for the edit, update and destroy actions
	def find_review
		@review = Review.find(params[:id])
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	def index
		@topics = Topic.all
	end

	def show
		@user
		@topic = Topic.find(params[:id])
	end

	def new
		@topic = Topic.new
	end

	def create
		@topic = Topic.new(topic_params)
		if @topic.save
			redirect_to topics_url
		else
			redirect_to 'new'
		end
	end

	def edit
		@topic = Topic.find(params[:id])
	end

	def update
		@topic = Topic.find(params[:id])
		if @topic.update(topic_params)
			redirect_to topic_path(@topic)
		else
			render 'edit'
		end
	end

	def destroy
		@topic.destroy
		redirect_to topics_path
	end


	private

	def topic_params
		params.require(:topic).permit(:title, :content)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = current_user.id
	end

	def show
		@user = current_user.id
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<section>
	<p><%=comment.user.email %> replied:</p>
	<p>posted: <%= comment.created_at %></p>
	<p><%= comment.comment %> </p>

	<!-- Signed in user can only edit and delete the reviews they created. If statement to check if user is signed and and that they match the user id stored on the individual review, then the edit and delete buttons will be visible. -->
	<% if user_signed_in? %>

		<% if comment.user_id == current_user.id %>

		<%= link_to 'Edit', edit_topic_comment_path(comment.topic, comment) %>
		<%= link_to 'Delete', topic_comment_path(comment.topic, comment), method: :delete, data: { 
			confirm: "Are you sure?" } %>

		<% end %>
	<% end %>
</section>

app/views/comments/_form.html.erb
<div class="form-group">
	<%= form_for([@topic, @topic.comments.build]) do |f| %>

		<%= f.text_area :comment, class: "form-control" %><br>
		<%= f.submit "Submit Comment", class: "btn btn-default" %>
	<% end %>
</div>

<%= link_to 'Cancel and return to topic', topic_path(@topic) %>

app/views/comments/edit.html.erb
<h1>Edit Your Comment</h1>

<%= form_for([@topic, @comment]) do |f| %>
	<%= f.text_area :comment %>
	<%= f.submit 'Update Comment' %>
<% end %>

<%= link_to 'Cancel and return to topic', topic_path(@topic) %>

app/views/comments/new.html.erb
<h3>Enter comment</h3>

<%= render 'form' %>

app/views/landings/index.html.erb
<% if user_signed_in? %>
<h1>Welcome!</h1>
<h3>Choose from Product Reviews to start reviewing some of your favorite items on the market.</h3>

<h3>Or hop into the Forum to chat about the latest news and topics in the makeup industry!</h3>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeupalleyrevampApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/latest/css/font-awesome.css" rel="stylesheet">
  </head>

  <header>
  </header>
   <h1 class="hero-title">MakeupAlley</h1>


  <body>
  	<% if notice %>
  	  <p class="alert alert-success"><%= notice %></p>
  	<% end %>
  	<% if alert %>
  	  <p class="alert alert-danger"><%= alert %></p>
  	<% end %>

    <nav class="navbar-default">
      <div class="container">

          <% if user_signed_in? %>
          <div class="navbar-header navbar-brand">Hello <strong><%= current_user.email %></strong></div>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Edit profile', edit_user_registration_path, class: "navbar-brand" %> </li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-brand" %></li>
          </ul>
            
          <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Sign up", new_user_registration_path, class: "navbar-brand" %></li>
            <li><%= link_to "Login", new_user_session_path, class: "navbar-brand" %></li>
          </ul>  
          <% end %>

    <% if user_signed_in? %>
        <div class="navbar-header .col-md-4">
          <%= link_to "Product Reviews", products_path, class: "navbar-brand" %>
          <%= link_to "Forum", topics_path, class: "navbar-brand" %>
        </div>
      </div>
    </nav>

 <% end %>
 
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/products/edit.html.erb
<h1>This is the Product Edit Page</h1>

<h1> Tell us what you think! </h1>

<%= form_for @product do |f| %>

	<div class="form-group">
 	<%= f.fields_for :review do |rc_fields| %>
	   <%= rc_fields.text_field :title, placeholder: 'Title', class: "form-control" %><br>
	    <%= rc_fields.text_area :review, placeholder: 'Review', class: "form-control" %><br>
	    <%= rc_fields.number_field :rating, placeholder: 'Rating', class: "form-control" %><br>
	</div>
  		<%= f.submit "Submit Review", class: "btn btn-default" %>
  	<% end %>
<% end %>
<br>
<%= link_to 'Cancel and go back to Product', product_path(@product) %>

app/views/products/index.html.erb
<h2>Products Index</h2>
<%= link_to "Add A Product", new_product_path %>

<div class="row">

<% @products.each do |product| %>
	<div class="col-md-10">
		<ul class="products-list">
			<%= link_to product do %>
				<li><%= product.name %></li>
			<% end %>
		</ul>
	</div>
<% end %>

</div>

app/views/products/new.html.erb
<h1>This is the Product New Page</h1>

<h1> Tell us what you think! </h1>

<%= form_for @product do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :image %>
    <%= f.text_field :img, class: 'form-control' %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <%= f.submit "Submit", class: "btn btn-default" %>
  <% end %>

<%= link_to "Back to Products", products_path %>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<img src="<%= @product.img %>"/>

<h2>Average Rating</h2>
<!-- The div average-review-rating will evaluate the data score which pulls in the average_review instance variable stored in the Products Controller -->
<div class="average-review-rating" data-score=<%= @average_review %>></div>

<div class="product-description">
	<p><%= @product.description %></p>
</div>
<div>
	<%= link_to 'Delete', product_path(@product), method: :delete, data: { 
		confirm: "Are you sure?" } %>
</div>

<div class="write-review">
	<%= link_to 'Write a Review', new_product_review_path(@product) %>
</div><br>

<div>
	<%= render @product.reviews %>
</div>

<!-- script tag provided by Jacob Overgaard's raty-fa.js (details in README) -->
<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function(){
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
$('.average-review-rating').raty({
	readOnly: true,
	path: '/assets/',
	score: function(){
		return $(this).attr('data-score')
	}
});
</script>

app/views/reviews/_form.html.erb
<div class="form-group">
	<%= simple_form_for([@product, @product.reviews.build]) do |f| %>
		<%= f.text_field :title, placeholder: 'Title', class: "form-control" %><br>
		<%= f.text_area :review, placeholder: 'Review', class: "form-control"  %><br>
		<!-- ID on div will be targeted by the script so that it will replace the original input for rating -->
		<div id="rating-form"><label>Rating</label></div>
		<%= f.submit "Submit Review", class: 'btn btn-default' %>
	<% end %>
</div>

<%= link_to 'Cancel and return to product', product_path(@product) %>

<!-- script tag provided by Jacob Overgaard's raty-fa.js (details in README) -->
<script>
$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>

app/views/reviews/_review.html.erb
<section>
	<p> Title: <%= review.title %> </p>
	<p> Author: <%= review.user.email %> </p>
	<p> <%= review.review %> </p>
	<div class="review-rating" data-score="<%= review.rating %>"></div>

	<!-- Signed in user can only edit and delete the reviews they created. If statement to check if user is signed and and that they match the user id stored on the individual review, then the edit and delete buttons will be visible. -->
	<% if user_signed_in? %>

		<% if review.user_id == current_user.id %>

		<%= link_to 'Edit', edit_product_review_path(review.product, review) %>
		<%= link_to 'Delete', product_review_path(review.product, review), method: :delete, data: { 
			confirm: "Are you sure?" } %>

		<% end %>
	<% end %>
</section>

app/views/reviews/edit.html.erb
<h1>Edit Your Review</h1>

<div class="form-group">
	<%= form_for([@product, @review]) do |f| %>
		<%= f.text_field :title, class: "form-control" %>
		<%= f.text_area :review, class: "form-control" %>
		<div id="rating-form"><label>Rating</label></div>
		<%= f.submit 'Update Review', class: "btn btn-default" %>
	<% end %>
</div>
<%= link_to 'Cancel and return to product', product_path(@product) %>

<script>
$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>

app/views/reviews/new.html.erb
<h2>Tell us what you think!</h2>

<%= render 'form' %>

app/views/topics/edit.html.erb
<h1>Edit Your Topic</h1>

<%= simple_form_for @topic do |t| %>
	<%= t.input :title %>
	<%= t.input :content %>
	<%= t.button :submit %>
<% end %>

<%= link_to 'Cancel and return to topic', topic_path(@topic) %>

app/views/topics/index.html.erb
<h1>Member Forum</h1>
<h4>Chat with members about all things Makeup!</h4>
<div><h2><%= link_to 'Add a new Topic!', new_topic_path %></h2></div>

<div>
	<h4>Latest Topics</h4>
	<% @topics.each do |t| %>

		<ul>
			<%= link_to t do %>
				<li><%= t.title %></li>
			<% end %>
		</ul>
	<% end %>

</div>

app/views/topics/new.html.erb
<%= simple_form_for @topic do |t| %>
	<%= t.input :title %>
	<%= t.input :content %>
	<%= t.button :submit %>
<% end %>

app/views/topics/show.html.erb
<h3><%= @topic.title %></h3>

<%= @topic.content %><br>

<h3><%= link_to 'Reply', new_topic_comment_path(@topic) %></h3>

<%= render @topic.comments %>